[tool.flakeheaven]
format = "grouped"
show_source = true
statistics = false
doctests = false
enable_extensions = "G"

exclude = ["falc/tests", "tests"]

accept_encodings = "utf-8"
max_line_length = 99

max_jones_score = 12
max_cognitive_score = 15
max_try_body_length = 4
max_arguments = 5
max_methods = 8
max_local_variables = 7
max_expressions = 12
max_returns = 5
max_function_expressions = 6
max_line_complexity = 17
max_module_expressions = 7
max_cognitive_average = 8
max_string_usages = 5
max_imports = 12
max_attributes = 6
max_module_members = 7
max_imported_names = 50
max_import_from_members = 9

max_base_classes = 3
max_decorators = 5
max_awaits = 5
max_asserts = 5
max_call_level = 3
max_annotation_complexity = 3

max_tuple_unpack_length = 4
max_access_level = 4

[tool.flakeheaven.plugins]
"flake8-annotations" = ["-*", "+ANN001", "+ANN2??", "+ANN301"]
"flake8-bandit" = ["+*"]
"wemake-python-styleguide" = ["-*", "+WPS2??", "-WPS220", "-WPS214", "-WPS237"]
"pycodestyle" = ["-E501"]